version: '3.1'

services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_ROOT_PASSWORD=secret'
      - 'MARIADB_USER=myuser'
      - 'MARIADB_PASSWORD=myuser_pw'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:7-alpine'
#    restart: unless-stopped
    ports:
      - '6379'