version: '3.1'

services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_ROOT_PASSWORD=secret'
      - 'MARIADB_USER=myuser'
      - 'MARIADB_PASSWORD=myuser_pw'
    ports:
    # spring-boot-starter-docker-compose 를 사용하면 port를 expose 하지 않아도 됩니다.
    # intellij 를 사용한다면 spring debugger plugin을 설치해주세요.
      - '3306'
  redis:
    image: 'redis:7-alpine'
#    restart: unless-stopped
    ports:
      - '6379'